name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  intl: ^0.18.1
  lottie: ^2.6.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  uuid: ^4.1.0
  clipboard: ^0.1.3
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/resources/assets/animations/
